# Generated by Django 5.1.4 on 2025-02-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qno', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('qtext', models.CharField(default='null', max_length=500)),
                ('answer', models.CharField(default='null', max_length=500)),
                ('op1', models.CharField(default='null', max_length=250)),
                ('op2', models.CharField(default='null', max_length=250)),
                ('op3', models.CharField(default='null', max_length=250)),
                ('op4', models.CharField(default='null', max_length=250)),
                ('subject', models.CharField(choices=[('dsa', 'Data Structures and Algorithms'), ('os', 'Operating Systems'), ('dbms', 'Database Management Systems'), ('cn', 'Computer Networks'), ('ai', 'Artificial Intelligence'), ('ml', 'Machine Learning'), ('se', 'Software Engineering'), ('coa', 'Computer Organization and Architecture'), ('toc', 'Theory of Computation'), ('cloud', 'Cloud Computing'), ('cybersec', 'Cyber Security'), ('iot', 'Internet of Things')], default='dsa', max_length=50)),
            ],
            options={
                'db_table': 'Question',
            },
        ),
    ]
